version: '3'

services:
  csam:
    build:
      context: .
      dockerfile: ./Dockerfile
    platform: "linux/amd64"
    env_file:
      - .env
    command: yarn start
    ports:
      - "6000:6000"